spring.application.name=week9_SpringBootWebFluxRest
server.port=8084
 
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=centennial
spring.main.web-application-type=reactive
 
logging.level.org.springframework=ERROR
logging.level.com=TRACE