spring.application.name=week10_MicroServiceEurekaServer
server.port=8761

eureka.server.enable-self-preservation=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# 清理无效节点的时间间隔（单位毫秒，默认 60000 即 60秒）
eureka.server.eviction-interval-timer-in-ms=5000

logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF

